services:
  rabbitmq:
    image: rabbitmq:3-management
    restart: unless-stopped
    links:
      - mongodb
    ports:
      - "5672:5672"

  mongodb:
    image: mongo:3.2
    restart: unless-stopped
    volumes:
      - ${PROWES_DATA_DIR:-../data/pro_wes}/db:/data/db
    ports:
      - "27017:27017"

  flower:
    image: mher/flower:0.9.7
    restart: unless-stopped
    command: flower --broker=amqp://guest:guest@rabbitmq:5672// --port=5555
    ports:
      - "5555:5555"
