openapi: 3.0.0
info:
  title: Workflow Execution Service
  version: 1.0.0

paths:
  /service-info:
    get:
      summary: Get information about Workflow Execution Service.
      description: |-
        May include information related (but not limited to) the workflow descriptor formats, versions supported, the WES API versions supported, and information about general service availability.
      x-swagger-router-controller: ga4gh.wes.server
      operationId: GetServiceInfo
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/definitions/ServiceInfo'
        '400':
          description: The request is malformed.
          content:
            application/json:
              schema:
                $ref: '#/definitions/ErrorResponse'
        '401':
          description: The request is unauthorized.
          content:
            application/json:
              schema:
                $ref: '#/definitions/ErrorResponse'
        '403':
          description: The requester is not authorized to perform this action.
          content:
            application/json:
              schema:
                $ref: '#/definitions/ErrorResponse'
        '500':
          description: An unexpected error occurred.
          content:
            application/json:
              schema:
                $ref: '#/definitions/ErrorResponse'
      tags:
        - WorkflowExecutionService
  /runs:
    get:
      summary: List the workflow runs.
      description: >-
        This list should be provided in a stable ordering.
        (The actual ordering is implementation dependent.)
        When paging through the list, the client should
        not make assumptions about live updates, but should assume the
        contents of the list reflect the workflow list at the moment
        that the first page is requested.  To monitor a specific
        workflow run, use GetRunStatus or GetRunLog.
      x-swagger-router-controller: ga4gh.wes.server
      operationId: ListRuns
      parameters:
        - name: page_size
          description: >-
            OPTIONAL
            The preferred number of workflow runs to return in a page.
            If not provided, the implementation should use a default page size.
            The implementation must not return more items
            than `page_size`, but it may return fewer.  Clients should
            not assume that if fewer than `page_size` items are
            returned that all items have been returned.  The
            availability of additional pages is indicated by the value
            of `next_page_token` in the response.
          in: query
          schema:
            type: string
            format: int64
        - name: page_token
          description: >-
            OPTIONAL
            Token to use to indicate where to start getting results. If unspecified, return the first
            page of results.
          in: query
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/definitions/RunListResponse'
        '400':
          description: The request is malformed.
          content:
            application/json:
              schema:
                $ref: '#/definitions/ErrorResponse'
        '401':
          description: The request is unauthorized.
          content:
            application/json:
              schema:
                $ref: '#/definitions/ErrorResponse'
        '403':
          description: The requester is not authorized to perform this action.
          content:
            application/json:
              schema:
                $ref: '#/definitions/ErrorResponse'
        '500':
          description: An unexpected error occurred.
          content:
            application/json:
              schema:
                $ref: '#/definitions/ErrorResponse'
      tags:
        - WorkflowExecutionService
    post:
      summary: Run a workflow.
      description: >-
        This endpoint creates a new workflow run and
        returns a `RunId` to monitor its progress.


        The `workflow_attachment` array may be used to upload files
        that are required to execute the workflow, including the primary
        workflow, tools imported by the workflow, other files
        referenced by the workflow, or files which are part of the
        input.  The implementation should stage these files to a
        temporary directory and execute the workflow from there.
        These parts must have a Content-Disposition header with a
        "filename" provided for each part.  Filenames may include
        subdirectories, but must not include references to parent
        directories with '..' -- implementations should guard against
        maliciously constructed filenames.


        The `workflow_url` is either an absolute URL to a workflow
        file that is accessible by the WES endpoint, or a relative URL
        corresponding to one of the files attached using
        `workflow_attachment`.


        The `workflow_params` JSON object specifies input parameters,
        such as input files.  The exact format of the JSON object
        depends on the conventions of the workflow language being
        used.  Input files should either be absolute URLs, or relative
        URLs corresponding to files uploaded using
        `workflow_attachment`.  The WES endpoint must understand and
        be able to access URLs supplied in the input.  This is
        implementation specific.
 
 
        The `workflow_type` is the type of workflow language and
        must be "CWL" or "WDL" currently (or another alternative 
        supported by this WES instance).
 
 
        The `workflow_type_version` is the version of the workflow language
        submitted and must be one supported by this WES instance.


        See the `RunRequest` documentation for details about other fields.
      x-swagger-router-controller: ga4gh.wes.server
      operationId: RunWorkflow
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/definitions/RunId'
        '400':
          description: The request is malformed.
          content:
            application/json:
              schema:
                $ref: '#/definitions/ErrorResponse'
        '401':
          description: The request is unauthorized.
          content:
            application/json:
              schema:
                $ref: '#/definitions/ErrorResponse'
        '403':
          description: The requester is not authorized to perform this action.
          content:
            application/json:
              schema:
                $ref: '#/definitions/ErrorResponse'
        '500':
          description: An unexpected error occurred.
          content:
            application/json:
              schema:
                $ref: '#/definitions/ErrorResponse'
      consumes:
         - multipart/form-data
      parameters:
        - in: formData
          name: workflow_params
          schema:
            type: string
            format: application/json

        - in: formData
          name: workflow_type
          schema:
            type: string

        - in: formData
          name: workflow_type_version
          schema:
            type: string

        - in: formData
          name: tags
          schema:
            type: string
            format: application/json

        - in: formData
          name: workflow_engine_parameters
          schema:
            type: string
            format: application/json

        - in: formData
          name: workflow_url
          schema:
            type: string

        - in: formData
          name: workflow_attachment
          schema: 
            type: array
            items:
              type: string
              format: binary
      tags:
        - WorkflowExecutionService
  /runs/{run_id}:
    get:
      summary: Get detailed info about a workflow run.
      description: >-
        This endpoint provides detailed information about a given workflow run.
        The returned result has information about the outputs produced by this workflow
        (if available), a log object which allows the stderr and stdout to be retrieved,
        a log array so stderr/stdout for individual tasks can be retrieved,
        and the overall state of the workflow run (e.g. RUNNING, see the State section).
      x-swagger-router-controller: ga4gh.wes.server
      operationId: GetRunLog
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/definitions/RunLog'
        '401':
          description: The request is unauthorized.
          content:
            application/json:
              schema:
                $ref: '#/definitions/ErrorResponse'
        '404':
          description: The requested workflow run not found.
          content:
            application/json:
              schema:
                $ref: '#/definitions/ErrorResponse'
        '403':
          description: The requester is not authorized to perform this action.
          content:
            application/json:
              schema:
                $ref: '#/definitions/ErrorResponse'
        '500':
          description: An unexpected error occurred.
          content:
            application/json:
              schema:
                $ref: '#/definitions/ErrorResponse'
      parameters:
        - name: run_id
          in: path
          required: true
          schema:
            type: string
      tags:
        - WorkflowExecutionService
  /runs/{run_id}/cancel:
    post:
      summary: Cancel a running workflow.
      x-swagger-router-controller: ga4gh.wes.server
      operationId: CancelRun
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/definitions/RunId'
        '401':
          description: The request is unauthorized.
          content:
            application/json:
              schema:
                $ref: '#/definitions/ErrorResponse'
        '404':
          description: The requested workflow run wasn't found.
          content:
            application/json:
              schema:
                $ref: '#/definitions/ErrorResponse'
        '403':
          description: The requester is not authorized to perform this action.
          content:
            application/json:
              schema:
                $ref: '#/definitions/ErrorResponse'
        '500':
          description: An unexpected error occurred.
          content:
            application/json:
              schema:
                $ref: '#/definitions/ErrorResponse'
      parameters:
        - name: run_id
          in: path
          required: true
          schema:
            type: string
      tags:
        - WorkflowExecutionService
  /runs/{run_id}/status:
    get:
      summary: Get quick status info about a workflow run.
      description: >-
        This provides an abbreviated (and likely fast depending on implementation)
        status of the running workflow, returning a simple result with the 
        overall state of the workflow run (e.g. RUNNING, see the State section).
      x-swagger-router-controller: ga4gh.wes.server
      operationId: GetRunStatus
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/definitions/RunStatus'
        '401':
          description: The request is unauthorized.
          content:
            application/json:
              schema:
                $ref: '#/definitions/ErrorResponse'
        '404':
          description: The requested workflow run wasn't found.
          content:
            application/json:
              schema:
                $ref: '#/definitions/ErrorResponse'
        '403':
          description: The requester is not authorized to perform this action.
          content:
            application/json:
              schema:
                $ref: '#/definitions/ErrorResponse'
        '500':
          description: An unexpected error occurred.
          content:
            application/json:
              schema:
                $ref: '#/definitions/ErrorResponse'
      parameters:
        - name: run_id
          in: path
          required: true
          schema:
            type: string
      tags:
        - WorkflowExecutionService