server:
    host: '0.0.0.0'
    port: 8080
    debug: True
    environment: development
    testing: False
    use_reloader: False

db:
    host: mongodb
    port: 27017
    dbs:
        prowes-db:
            collections:
                service_info:
                    indexes:
                        - keys:
                              id: 1
                          options:
                            'unique': True
                runs:
                    indexes:
                        - keys:
                              - run_id: ASCENDING
                                task_id: ASCENDING
                          options:
                            'unique': True
                            'sparse': True
api:
    specs:
        - path:
            - 20181010.be85140.workflow_execution_service.swagger.yaml
          append: null
          add_operation_fields:
              x-openapi-router-controller: ga4gh.wes.server
          connexion:
              strict_validation: True
              validate_responses: True
              options:
                  swagger_ui: True
                  serve_spec: True

log:
    version: 1
    disable_existing_loggers: False
    formatters:
        standard:
            class: logging.Formatter
            style: "{"
            format: "[{asctime}: {levelname:<8}] {message} [{name}]"
    handlers:
        console:
            class: logging.StreamHandler
            level: 20
            formatter: standard
            stream: ext://sys.stderr
    root:
        level: 10
        handlers: [console]

exceptions:
    required_members: [['message'], ['code']]
    status_member: ['code']
    exceptions: pro_wes.errors.exceptions.exceptions

endpoints:
    objects:
        id_charset: 'string.ascii_letters + string.digits + ".-_~"'
        id_length: 6
    access_methods:
        id_charset: 'string.ascii_letters + string.digits + ".-_~"'
        id_length: 6
    url_prefix: http
    external_host: 193.166.24.114
    external_port: 8080
    api_path: ga4gh/wes/v1