server:
    host: '0.0.0.0'
    port: 8080
    debug: True
    environment: development
    testing: False
    use_reloader: False

db:
    host: mongodb
    port: 27017
    dbs:
        prowes-db:
            collections:
                service_info:
                    indexes:
                runs:
                    indexes:
                        - keys:
                              - run_id: ASCENDING
                                task_id: ASCENDING
                          options:
                            'unique': True
                            'sparse': True
api:
    specs:
        - path:
            - 20181010.be85140.workflow_execution_service.swagger.yaml
          append: null
          add_operation_fields:
              x-openapi-router-controller: ga4gh.wes.server
          connexion:
              strict_validation: True
              validate_responses: True
              options:
                  swagger_ui: True
                  serve_spec: True

log:
    version: 1
    disable_existing_loggers: False
    formatters:
        standard:
            class: logging.Formatter
            style: "{"
            format: "[{asctime}: {levelname:<8}] {message} [{name}]"
    handlers:
        console:
            class: logging.StreamHandler
            level: 20
            formatter: standard
            stream: ext://sys.stderr
    root:
        level: 10
        handlers: [console]

exceptions:
    required_members: [['message'], ['code']]
    status_member: ['code']
    exceptions: trs_filer.errors.exceptions.exceptions

endpoints:
    service:
        url_prefix: https
        external_host: trs-filer-alex.c03.k8s-popup.csc.fi
        external_port: 443
        api_path: ga4gh/trs/v2
    service_info:
        id: "TEMPID1"
        name: "TEMP_STUB"
        type:
            group: "TEMP_GROUP"
            artifact: "TEMP_ARTIFACT"
            version: "v1"
        description: "Description of service."
        organization:
            name: "Parent organization"
            url: "parent/abc"
        contactUrl: "contact/abc"
        documentationUrl: "docs/abc"
        createdAt: "2020-01-01"
        updatedAt: "2020-01-01"
        environment: "ENV"
        version: "0.0.0"
    tool:
        id:
            charset: string.ascii_uppercase + string.digits
            length: 6
        meta_version:
            init: 1
            increment: 1
    version:
        id:
            charset: string.ascii_lowercase + string.digits
            length: 6
        meta_version:
            init: 1
            increment: 1
    toolclass:
        id:
            charset: string.ascii_lowercase + string.digits
            length: 6
        meta_version:
            init: 1
            increment: 1
        validation: False