---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.prowes.appName }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.prowes.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.prowes.appName }}
    spec:
      initContainers:
        - name: vol-init
          image: busybox
          command: [ 'mkdir' ]
          args: [ '-p', '/data/db', '/data/specs' ]
          volumeMounts:
            - mountPath: /data
              name: prowes-volume
      containers:
      - name: prowes
        image: {{ .Values.prowes.image }}
        imagePullPolicy: Always
        workingDir: '/app/pro_wes'
        command: [ 'gunicorn' ]
        args: [ '--log-level', 'debug', '-c', 'config.py', 'wsgi:app' ]
        env:
        - name: MONGO_HOST
          value: {{ .Values.mongodb.appName}}
        - name: MONGO_PORT
          value: "27017"
        - name: MONGO_USERNAME
          valueFrom:
            secretKeyRef:
              key: database-user
              name: {{ .Values.mongodb.appName }}
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              key: database-password
              name: {{ .Values.mongodb.appName }}
        - name: MONGO_DBNAME
          valueFrom:
            secretKeyRef:
              key: database-name
              name: {{ .Values.mongodb.appName }}
        - name: RABBIT_HOST
          value: {{ .Values.rabbitmq.appName}}
        - name: RABBIT_PORT
          value: "5672"
        livenessProbe:
          tcpSocket:
            port: prowes-port
          initialDelaySeconds: 5
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /ga4gh/wes/v1/service-info
            port: prowes-port
          initialDelaySeconds: 3
          periodSeconds: 3
        ports:
        - containerPort: 8080
          name: prowes-port
        volumeMounts:
        - mountPath: /data
          name: prowes-volume
      volumes:
      - name: prowes-volume
        persistentVolumeClaim:
          claimName: {{ .Values.prowes.appName}}-volume
